package test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/require"
)

// TestKSeF validates every golden XML document in test/data/gobl.ksef/out
// against the FA3 schema. The documents themselves are generated by
// TestGOBLToKSeF, which owns the `--update` flag; this test only checks that
// what is committed is schema-valid.
//
// Run without XSD validation (a no-op):
//
//	go test ./test -run TestKSeF -v
//
// Run with XSD validation (requires libxml2):
//
//	go test -tags xsdvalidate ./test -run TestKSeF -v
func TestKSeF(t *testing.T) {
	outPath := GetOutPath()

	entries, err := os.ReadDir(outPath)
	require.NoError(t, err)

	var found int
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".xml") {
			continue
		}
		found++

		name := entry.Name()
		t.Run(name, func(t *testing.T) {
			xmlData, err := os.ReadFile(filepath.Join(outPath, name))
			require.NoError(t, err, "failed to read XML file")

			t.Logf("Validating %s (%d bytes)", name, len(xmlData))
			ValidateAgainstFA3Schema(t, xmlData)
		})
	}

	// Guard against the whole suite silently passing because the directory
	// layout moved and nothing was picked up.
	require.NotZero(t, found, "no golden XML documents found in %s", outPath)
}
